language: ruby

dist: trusty

addons:
  apt:
    packages:
      - shellcheck

before_install:
  - git fetch --tags

before_script:
  - export TERRAFORM_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
  - curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
  - unzip terraform.zip; rm -f terraform.zip; chmod +x terraform
  - mkdir -p ${HOME}/bin; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
  - terraform -v

script:
  - ./scripts/ci.sh
