name: CI Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    defaults:
      run:
        shell: "bash"
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: v0.50.3

      - name: Run CI Script
        run: ./scripts/ci.sh
