name: CI Build

on:
  - push

jobs:
  build:
    name: Building with Terraform version ${{ matrix.terraform_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: ["0.12.31", "1.0.11"]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.47.0

      - name: Run CI Script
        run: ./scripts/ci.sh
