name: CI Build

on:
  - push

env:
  TFLINT_VERSION: "v0.33.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare bin directory
        run: |
          mkdir -p ${HOME}/bin
          echo '${HOME}/bin/' >> $GITHUB_PATH

      - name: Install shellcheck
        run: |
          wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz"
          tar -xvf shellcheck-stable.linux.x86_64.tar.xz
          cp shellcheck-stable/shellcheck ${HOME}/bin/
          shellcheck --version

      - name: Install terraform
        run: |
          export TERRAFORM_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
          curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
          unzip terraform.zip; rm -f terraform.zip; chmod +x terraform; mv terraform ${HOME}/bin/
          terraform -v

      - name: Install tflint
        run: |
          wget -O tflint.zip "https://github.com/wata727/tflint/releases/download/${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip"
          unzip tflint.zip
          mkdir -p ~/tflint/bin/
          install tflint ~/tflint/bin/
          echo '~/tflint/bin/' >> $GITHUB_PATH
          tflint -v

      - name: Cache tflint
        uses: actions/cache@v2
        with:
          path: ~/tflint/bin/
          key: ${{ runner.os }}-tflint-${{ env.TFLINT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-tflint-

      - name: Run CI Script
        run: ./scripts/ci.sh
