name: CI Build

on:
  - push

env:
  TFLINT_VERSION: "v0.33.1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: [0.12.x, 0.13.x, 0.14.x, 0.15.x, 1.0.11, latest]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare bin directory
        run: |
          mkdir -p ${HOME}/bin
          echo '${HOME}/bin/' >> $GITHUB_PATH

      - name: Install shellcheck
        run: |
          wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz"
          tar -xvf shellcheck-stable.linux.x86_64.tar.xz
          cp shellcheck-stable/shellcheck ${HOME}/bin/
          shellcheck --version

      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Install tflint
        run: |
          wget -O tflint.zip "https://github.com/wata727/tflint/releases/download/${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip"
          unzip tflint.zip
          mkdir -p ~/tflint/bin/
          install tflint ~/tflint/bin/
          echo '~/tflint/bin/' >> $GITHUB_PATH
          tflint -v

      - name: Cache tflint
        uses: actions/cache@v2
        with:
          path: ~/tflint/bin/
          key: ${{ runner.os }}-tflint-${{ env.TFLINT_VERSION }}
          restore-keys: |
            ${{ runner.os }}-tflint-

      - name: Run CI Script
        run: ./scripts/ci.sh
