name: CI Build

on:
  - push

env:
  TFLINT_VERSION: "v0.33.1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: [0.12.31, 0.13.7, 0.14.11, 0.15.5, 1.0.11]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare bin directory
        run: |
          mkdir -p ${HOME}/bin
          echo '${HOME}/bin/' >> $GITHUB_PATH

      - name: Install shellcheck
        run: |
          wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz"
          tar -xvf shellcheck-stable.linux.x86_64.tar.xz
          cp shellcheck-stable/shellcheck ${HOME}/bin/
          rm -rf shellcheck-stable*
          shellcheck --version

      - name: Install terraform
        run: |
          export TERRAFORM_VERSION=$(curl -s https://checkpoint-api.hashicorp.com/v1/check/terraform | jq -r -M '.current_version')
          curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/${{ matrix.terraform_version }}/terraform_${{ matrix.terraform_version }}_linux_amd64.zip"
          unzip terraform.zip
          rm -f terraform.zip
          chmod +x terraform
          mv terraform ${HOME}/bin/

      - name: Install tflint
        run: |
          wget -O tflint.zip "https://github.com/wata727/tflint/releases/download/${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip"
          unzip tflint.zip
          install tflint ${HOME}/bin/
          rm -rf tflint*
          tflint -v

      - name: Run CI Script
        run: ./scripts/ci.sh
