name: CI Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_version: [0.12.x, 0.13.x, 0.14.x, 0.15.x, 1.0.11, latest]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare bin directory
        run: |
          mkdir -p ${HOME}/bin
          echo '${HOME}/bin/' >> $GITHUB_PATH

      - name: Install shellcheck
        run: |
          wget "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz"
          tar -xvf shellcheck-stable.linux.x86_64.tar.xz
          cp shellcheck-stable/shellcheck ${HOME}/bin/
          shellcheck --version

      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform_version }}

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest

      - name: Cache tflint plugin directory
        uses: actions/cache@v2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Run CI Script
        run: ./scripts/ci.sh
